title: Dr. Scott E. Allen
description: Neurophysics of Human Learning· Trust by Design · Implementation Science Made Easy

theme: minima

header_pages:
  - index.md
  - neurophysics.md
  - trust.md
  - implementation.md
  - bio.md
  - contact.md
